config/routes.rb
Rails.application.routes.draw do

 
  resources :movies, only: [:index,:show] 

  resources :screenings, only: [:show] do
  	resources :orders, only: [:new, :create]
  end


  namespace :manage do
    get '', to: 'static#dashboard', as: '/'
  	resources :auditoriums
    resources :movies
    resources :screenings
    resources :orders
  end

  root to: "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auditorium.rb
class Auditorium < ApplicationRecord
	has_many :movies

	def to_s
		self.name
	end
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :auditorium
  has_many :screenings
  has_many :orders, through: :screenings

  def to_s
  	self.title
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :screening
  belongs_to :movie

  

  validates :card, numericality: { only_integer: true }

  validates :email, format: { with: /\A\S+@.+\.\S+\z/,
    message: "must be an email address" }

  validates :name,  
	  :email, 
	  :card,
	  :exp,
	  presence: true

end

app/models/screening.rb
class Screening < ApplicationRecord
  after_validation :set_seating_capacity, on: :create

  belongs_to :movie
  has_many :orders

  validates :movie_id, 
	  presence: true

  def sold_out?
  	self.seats === 0
  end


  private

  def set_seating_capacity
  	self.seats = self.movie.auditorium.capacity unless self.movie.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base




end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  	@movies = Movie.all
  end

  def show
  	@movie = Movie.find(params[:id])
  	@screenings = @movie.screenings.all.order(start: :asc)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@screening = Screening.find(params[:screening_id])
		@order = @screening.orders.new
		if @screening.sold_out?
			redirect_to movie_path(@screening.movie)
		end
	end

	def create
		@screening = Screening.find(params[:screening_id])
		@order = @screening.orders.new(order_params)
		@order.movie = @screening.movie
		if @screening.sold_out?
			redirect_to new_screening_order_path(@screening)
		else
			if @order.save
				OrderMailer.order_confirmation(@order).deliver_later
				@order.screening.seats -= 1
				@order.screening.save
			else
				render 'new'
			end
		end
	end

	private

	def order_params
		params.require(:order).permit(
			:name,
		    :email,
		    :card,
		    :exp,
			)
	end
end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController

	def show
		@screening = Screening.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	def decorated_date(date)
	    if !date.blank?
	      date.strftime('%B %d, %Y %I:%M %P' )
	    end
	  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showtime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Showtime</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to 'Get Tickets', root_path, class: "nav-link" %></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Manage Movies', manage_path, class: "nav-link" %></a>
          </li>
      </div>
    </nav>
    <div class="container">
      <% if flash.present? %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<div class="row">
<% @movies.each do |movie| %>
	<div class="col-sm-12 col-md-12 col-lg-4">
		<div class="card">
		  <div class="card-body">
		    <h5 class="card-title"><%= movie %></h5>
		    <p class="card-text">Playing in auditorium <%= movie.auditorium %></p>
		  </div>
		  <ul class="list-group list-group-flush">
		  	<% movie.screenings.order(start: :asc).limit(6).each do |screening| %>
		    <li class="list-group-item"><%= decorated_date(screening.start) %>
		    	<% if screening.seats == 0 %>
		    		<%= link_to 'Sold Out', '#', class: "btn btn-primary float-right disabled" %>
		    	<% else %>
		    	<%= link_to 'Buy Ticket', new_screening_order_path(screening), class: "btn btn-primary float-right" %>
		    	<% end %>
		    </li>
		    <% end %>
		  </ul>
		  <div class="card-body">
		    <%= link_to 'View more screenings', movie_path(movie) %>
		  </div>
		</div>
	</div>
<% end %>
</div>

app/views/movies/show.html.erb
<h1><%= @movie %></h1>

<div class="table-responsive">
  <table class="table table-bordered">
 
  <tbody>
  	<% @screenings.each do |screening| %>
    <tr class="text-center">
      <td><p class="lead"><%= decorated_date(screening.start) %></p></td>
      <td>
        <% if screening.seats == 0 %>
          <%= link_to 'Sold Out', '#', class: "btn btn-primary btn-lg disabled" %>
        <% else %>
          <%= link_to 'Buy Ticket', new_screening_order_path(screening), class: "btn btn-primary btn-lg" %>
        <% end %>
        </td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/orders/create.html.erb
<div class="jumbotron text-center">
	<h1>Thank You For Your Order</h1>
</div>

app/views/orders/new.html.erb
<p><%= link_to 'cancel', :back, class: "float-right" %></p>
<h1>Buy a Ticket for <%= decorated_date(@order.screening.start) %> showing of <%= @order.screening.movie %></h1>
<hr/>
<div class="jumbotron">
	<% if @order.screening.sold_out? %>
		<h1>This movie is sold out</h1>
	<% else %>
		<%= simple_form_for @order, url: screening_orders_path do |f| %>
			<%= f.input :name %>
			<%= f.input :email %>
			<%= f.input :card %>
			<%= f.input :exp %>
		<%= f.submit %>
		<% end %>
	<% end %>
</div>